### ISSUE TITLE
Server crashing because of spark (Different to the previous issue)

### ISSUE THREAD

**Issue by redstonerti** [lucko/spark#274]
Ever since moving my server to linux, spark kills the server whenever it does anything. I tried spark versions 1.9.45 and 1.10.9, I'm playing on fabric 1.19 and am on a fresh install arch linux.
Here's the jvm crash: https://mclo.gs/sMc5vna
Here's latest.log: https://mclo.gs/e0GUhkw
No crash report gets generated.
CPU: 7950x
Ram: 64GB DDR5@5600MT/s

**Comment by lucko** [comment]
I've implemented a temporary solution: 

<img width="986" alt="Screenshot 2022-11-27 at 23 37 31" src="https://user-images.githubusercontent.com/8352868/204165867-64414f53-efe1-47cd-b91e-cc3bf6bad076.png">

Unfortunately the problem is with async-profiler (the library the spark uses to gather profiling data) so there's not much I can do to resolve it. I have just updated spark to use the latest version though - so hopefully that will help!

**Comment by redstonerti** [comment]
Are you aware that --force-java-sampler avoids the crash?

**Comment by lucko** [comment]
After the 2nd startup it should be fine. You can also use this option in the spark config file: https://spark.lucko.me/docs/Configuration#backgroundprofilerengine (set it to "java")

**Comment by redstonerti** [comment]
It is not fine after the second startup. It doesn't crash on startup if I set background profiler engine to java, but It still crashes a lot. I tried starting it up again after stopping it once and it crashes again. After that, it also crashed on startup. In order for it not to crash on startup, I had to close the server, remove spark, run the server, close it, add spark again and run it again. There was no other way. Could you please make an issue in the library that you use? Spark is a really useful mod and it's unusable for me right now. Thanks.
